name: Actions

on: workflow_dispatch

jobs:
  checkout-code:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Display Code
        run: |
          pwd
          ls
          cd ../
          ls