name: Artifacts

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: README.md

  job2:
    runs-on: self-hosted
    needs: job1
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Output content
        run: ls
