name: "Chain Jobs"

on:
  workflow_dispatch:
    inputs:
      docker:
        required: true
        type: boolean

jobs:
  job-1:
    runs-on: self-hosted
    steps:
      - name: step-1
        run: echo "step-1"
      - name: exit
        run: exit 1
  job-2:
    runs-on: self-hosted
    steps:
      - name: step-2
        run: echo "step-2"
  job-3:
    runs-on: self-hosted
    if: always()
    needs:
      - job-1
    steps:
      - name: step-3
        run: echo "step-3 ${{ github.event.inputs.docker }}"
  job-4:
    runs-on: self-hosted
    if: ${{ github.event.inputs.docker == 'true'}}
    steps:
      - name: step-4
        run: echo "runs only when run-docker input is set to true"