name: Containers
on: workflow_dispatch
jobs:
  job1:
    runs-on: self-hosted
    container:
      image: python:3.12.7-slim-bookworm
    steps:
      - name: "Inside container"
        run: python3 --version
  job2:
    runs-on: self-hosted
    steps:
      - name: "Outside container"
        run: python3 --version