name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello Prem"
        shell: bash
  good-bye:
    runs-on: ubuntu-latest
    steps:
      - name: hello2
        run: echo "Bye Bye"
        shell: bash