name: Containers
on: workflow_dispatch
jobs:
  job1:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: admin
    steps:
      - name: "Inside container"
        run: python3 --version